/*
var GATEWAY_APROVACAO_CC = 6;
var ANALISAR_SOLICITACAO_GESTOR = 8;
var ANALISAR_SOLICITACAO_DIRETOR = 9;
var FIM_APROVAR_DIRETOR = 7;
var FIM_REPROVAR_GESTOR = 15;
*/
var APROVA_N1 = 202;
var APROVA_N2 = 207;
var APROVA_N3 = 212;
var APROVA_N4 = 21;
var APROVA_N5 = 21;
var APROVA_N6 = 21;
var INTEGRA_REJEICAO = 113;